# Generated by Django 4.0.6 on 2022-10-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremp',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=50),
        ),
    ]
