# Generated by Django 4.0.6 on 2022-11-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0011_remove_permission_checkbox_permission_checkbox_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='role_id',
            new_name='Role_Id',
        ),
    ]
