# Generated by Django 4.0.6 on 2023-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0012_rename_role_id_permission_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media', verbose_name='photo'),
        ),
    ]
