# Generated by Django 4.0.6 on 2022-10-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0002_alter_useremp_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
