# Generated by Django 4.0.6 on 2022-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0003_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='usermaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('number', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=250, null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
    ]
