# Generated by Django 4.0.6 on 2022-11-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0007_rename_name_role_rolename'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('MenuId', models.IntegerField(primary_key=True, serialize=False)),
                ('MenuName', models.CharField(max_length=255, null=True)),
                ('MenuDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('MenuPath', models.CharField(blank=True, max_length=255, null=True)),
                ('MenuIcon', models.CharField(blank=True, max_length=255, null=True)),
                ('ParentId', models.IntegerField(blank=True, null=True)),
                ('MenuPostion', models.IntegerField(blank=True, null=True)),
                ('SortOrder', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
