# Generated by Django 4.0.6 on 2022-11-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0009_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='Role_Id',
            new_name='role_id',
        ),
    ]
