# Generated by Django 4.0.6 on 2022-11-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0010_rename_role_id_permission_role_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='checkbox',
        ),
        migrations.AddField(
            model_name='permission',
            name='checkbox_id',
            field=models.ManyToManyField(to='Empmaster.menuitem'),
        ),
    ]
