# Generated by Django 4.0.6 on 2023-06-07 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empmaster', '0013_usermaster_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='Image',
        ),
    ]
